<?php

$config=[
    'add_articles_rules'=>[
    [ 'field'=>'title',
       'label'=>'Title',
       'rules'=>'required'
    ],
    [
        'field'=>'body',
        'label'=>'Body',
        'rules'=>'required' 
    ]
    ],
    'add_login_rules'=>[
        [
            'field'=>'username',
            'label'=>'Username',
            'rules'=>'required|alpha|trim'
        ],
        [
            'field'=>'password',
            'label'=>'Password',
            'rules'=>'required'
        ],
        'signup_rules'=>[
            [
                'field'=>'username',
                'label'=>'Username',
                'rules'=>'required|alpha|trim'
            ],
            [
                'field'=>'password',
                'label'=>'Password',
                'rules'=>'required'
            ] ,
            [
                'field'=>'confirm_password',
                'label'=>'Confirm_password',
                'rules'=>'required'
            ],
            [
                'field'=>'email',
                'label'=>'email',
                'rules'=>'required'
            ],
            [
                'field'=>'city',
                'label'=>'city',
                'rules'=>'required'
            ]
        ]
    ]
];
?>